version: '3'

services:
  ctr-db:
    image: mysql:5.7
    volumes:
      - db-vol:/var/lib/mysql
    env_file:
      - env_var_ctr-db.txt
    networks:
      - wp-net
    restart: always

  ctr-wp:
    image: wordpress:latest
    ports:
      - "3000:80"
    env_file:
      - env_var_ctr-wp.txt
    networks:
      - wp-net
    restart: always
    depends_on:
      - ctr-db

  py-websever:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:7000"
    restart: always

volumes:
  db-vol: {}
networks:
  wp-net: {}