version: '3'

services:
  crt-db:
    image: mysql:5.7
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_USER: devoscloudbootcamp
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: devoscloudbootcamp
    networks:
      - wp-net
    restart: always

  crt-wp:
    image: wordpress:latest
    ports:
      - "3000:80"
    environment:
      WORDPRESS_DB_HOST: crt-db:3306
      WORDPRESS_DB_USER: devopscloudbootcamp
      WORDPRESS_DB_PASSWORD: devopscloudbootcamp
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp-net
    restart: always
    depends_on:
      - ctr-db

  py-webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:7000"
    restart: always

volumes:
  db-vol: {}
networks:
  wp-net: {}